# Generated by Django 5.0.4 on 2024-05-01 11:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_question_name_alter_quiz_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
